runtime: python38

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: <cloud-instance-name>=tcp:3306
  
  # Remember - storing secrets in plaintext is potentially unsafe. Consider using
  # something like https://cloud.google.com/secret-manager/docs/overview to help keep
  # secrets secret.
env_variables:
  CLOUD_SQL_CONNECTION_NAME: <cloud-instance-name>
  DB_USER: <db-username>
  DB_PASS: <db-password>
  DB_NAME: <database-name>
  DB_HOST: <db-host-ip>:3306
  UNAME: <admin-username>
  UEMAIL: <admin-email>
  UPASS: <admin-password>
  
