runtime: python38

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: shel-test-deploy:europe-west2:shel-test=tcp:3306
  
  # Remember - storing secrets in plaintext is potentially unsafe. Consider using
  # something like https://cloud.google.com/secret-manager/docs/overview to help keep
  # secrets secret.
env_variables:
  CLOUD_SQL_CONNECTION_NAME: bpi-shel:europe-west2:shel-test
  DB_USER: root
  DB_PASS: BestPractice
  DB_NAME: shel-test
  DB_HOST: 35.242.155.144:3306
  UNAME: Marina
  UEMAIL: marina.kaur-channing@ons.gov.uk
  UPASS: BPI2020
  