"""empty message

Revision ID: 6bb292ebbcba
Revises: 
Create Date: 2019-06-19 09:35:51.941953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb292ebbcba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logstakeholder', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logstakeholder', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logstakeholder', type_='foreignkey')
    op.drop_column('logstakeholder', 'user_id')
    # ### end Alembic commands ###
