"""empty message

Revision ID: aab95df189f9
Revises: fd11e8258ada
Create Date: 2019-06-18 10:11:41.666927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab95df189f9'
down_revision = 'fd11e8258ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_log_stakeholder_date', table_name='log_stakeholder')
    op.drop_index('ix_log_stakeholder_stakeholder_person', table_name='log_stakeholder')
    op.drop_table('log_stakeholder')
    op.drop_constraint(None, 'logstakeholder', type_='foreignkey')
    op.drop_constraint(None, 'logstakeholder', type_='foreignkey')
    op.drop_column('logstakeholder', 'user_id')
    op.drop_column('logstakeholder', 'user_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logstakeholder', sa.Column('user_username', sa.VARCHAR(length=64), nullable=False))
    op.add_column('logstakeholder', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'logstakeholder', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'logstakeholder', 'user', ['user_username'], ['username'])
    op.create_table('log_stakeholder',
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('stakeholder_person', sa.VARCHAR(length=120), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('user_username', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('user_username')
    )
    op.create_index('ix_log_stakeholder_stakeholder_person', 'log_stakeholder', ['stakeholder_person'], unique=False)
    op.create_index('ix_log_stakeholder_date', 'log_stakeholder', ['date'], unique=False)
    # ### end Alembic commands ###
